.TH KGAMEOFLIFE.KSS 1 "2014" "GameOfLife"
.SH NAME
gameoflife.kss
\- An OpenGL screensaver under water screensaver.
.SH SYNOPSIS
.B gameoflife.kss
[\fIQt\ options\fP] [\fIKDE\ options\fP] [\fIoptions\fP]
.SH DESCRIPTION
gameoflife is a screensaver.
.SH OPTIONS
.SS Options:
.TP
.B  \-\-setup
Setup screen saver
.TP
.BI  \-\-window\-id \ wid
Run in the specified XWindow
.TP
.B  \-\-root
Run in the root XWindow
.TP
.B  \-\-demo
Start screen saver in demo mode [default]
.SS Generic options:
.TP
.B  \-\-help
Show help about options
.TP
.B  \-\-help\-qt
Show Qt specific options
.TP
.B  \-\-help\-kde
Show KDE specific options
.TP
.B  \-\-help\-all
Show all options
.TP
.B  \-\-author
Show author information
.TP
.B \-v,  \-\-version
Show version information
.TP
.B  \-\-license
Show license information
.TP
.B  \-\-
End of options
.SS
.SS KDE options:
.TP
.BI  \-\-caption \ caption
Use
.IR caption
as name in the titlebar
.TP
.BI  \-\-icon \ icon
Use
.IR icon
as the application icon
.TP
.BI  \-\-config \ filename
Use alternative configuration file
.TP
.B  \-\-nocrashhandler
Disable crash handler, to get core dumps
.TP
.B  \-\-waitforwm
Waits for a
.B WM_NET
compatible windowmanager
.TP
.BI  \-\-style \ style
sets the application GUI style
.TP
.BI  \-\-geometry \ geometry
sets the client geometry of the main widget - see
.BR X (7)
for the argument format
.SS
.SS Qt options:
.TP
.BI  \-\-display \ displayname
Use the X-server display
.IR displayname
.TP
.BI  \-\-session \ sessionId
Restore the application for the given
.IR sessionId
.TP
.B  \-\-cmap
Causes the application to install a private color
map on an 8-bit display
.TP
.BI  \-\-ncols \ count
Limits the number of colors allocated in the color
cube on an 8-bit display, if the application is
using the
.B QApplication::ManyColor
color specification
.TP
.B  \-\-nograb
tells Qt to never grab the mouse or the keyboard
.TP
.B  \-\-dograb
running under a debugger can cause an implicit
.BR -nograb ,
.RB use \ -dograb
to override
.TP
.B  \-\-sync
switches to synchronous mode for debugging
.TP
.BI \-\-fn,\ \-\-font \ fontname
defines the application font
.TP
.BI \-\-bg,\ \-\-background \ color
sets the default background color and an
application palette (light and dark shades are
calculated)
.TP
.BI \-\-fg,\ \-\-foreground \ color
sets the default foreground
.RI color
.TP
.BI \-\-btn,\ \-\-button \ color
sets the default button
.RI color
.TP
.BI  \-\-name \ name
sets the application
.RI name
.TP
.BI  \-\-title \ title
sets the application caption
.RI title
.TP
.B  \-\-visual TrueColor
forces the application to use a TrueColor visual on
an 8-bit display
.TP
.BI  \-\-inputstyle \ inputstyle
sets XIM (X Input Method) input style. Possible
values are
.BR onthespot ,
.BR overthespot ,
.BR offthespot ,
.RB and \ root
.TP
.BI  \-\-im \ XIM\ server
set XIM server
.TP
.B  \-\-noxim
disable XIM
.TP
.B  \-\-reverse
mirrors the whole layout of widgets
.TP
.BI  \-\-stylesheet \ file.qss
applies the Qt stylesheet to the application widgets
.SS

.SH AUTHORS
JK <justyna.kaplinska@gmail.com>


.PP
This manual page was written by JK <justyna.kaplinska@gmail.com>.
Permission is granted to copy, distribute and/or modify this document under
the terms of the GNU General Public License, Version 2 or any later version
published by the Free Software Foundation.
